import { calculateYardage } from "@/lib/yardage";
import { emptyDesign, key } from "@/lib/custom-block";
const d = emptyDesign(4, "A");
d.cells[key(0,0)] = { kind:"hst", rotation:0, fabrics:["A","B"] };
d.cells[key(1,1)] = { kind:"qst", rotation:0, fabrics:["A","B","C","D"] };
delete d.cells[key(2,1)];
d.cells[key(2,0)] = { kind:"geese", rotation:0, fabrics:["C","A"] };
const s:any = { pattern:"custom-block", quiltWidth:60, quiltHeight:72, blockSize:12, borderWidth:4, sashingWidth:0, assignments:{sashing:"Y",border:"Z"}, fabricPhotos:{}, patchworkFabricCount:4, patchworkGrid:[], alternateBlocks:false, blockLayout:"straight", customBlock:d, customBlockB:null, useBlockB:false, customSwapPair:null, fabricPrices:{}, seamAllowance:0.25 };
const res:any = calculateYardage(s);
console.log(JSON.stringify(res, null, 1).slice(0, 2500));
