import { calculateYardage } from "@/lib/yardage";
import { usePlanner } from "@/lib/planner-store";
import { emptyDesign, key } from "@/lib/custom-block";
const d = emptyDesign(4, "A");
d.cells[key(0,0)] = { kind:"hst", rotation:0, fabrics:["A","B"] };
const base:any = { quiltWidth:60, quiltHeight:72, blockSize:12, borderWidth:4, sashingWidth:0, fabricWidth:42, safetyBuffer:0.1, assignments:{}, fabricPhotos:{}, alternateBlocks:false, blockLayout:"straight", customBlockB:null, useBlockB:false, customSwapPair:null };
void usePlanner;
const s:any = { ...base, ...(({} as any)), pattern:"custom-block", customBlock:d };
const r:any = calculateYardage(s);
for (const f of r.fabrics) console.log(f.fabric, "yards", f.yards, "strips", f.strips.map((x:any)=>[x.stripWidth,x.count]), "pieces", f.pieces.map((p:any)=>[p.label,p.count,p.w,p.h]));
