/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SizeRouteImport } from './routes/size'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as FabricsRouteImport } from './routes/fabrics'
import { Route as IndexRouteImport } from './routes/index'

const SizeRoute = SizeRouteImport.update({
  id: '/size',
  path: '/size',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricsRoute = FabricsRouteImport.update({
  id: '/fabrics',
  path: '/fabrics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fabrics': typeof FabricsRoute
  '/results': typeof ResultsRoute
  '/size': typeof SizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fabrics': typeof FabricsRoute
  '/results': typeof ResultsRoute
  '/size': typeof SizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fabrics': typeof FabricsRoute
  '/results': typeof ResultsRoute
  '/size': typeof SizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fabrics' | '/results' | '/size'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fabrics' | '/results' | '/size'
  id: '__root__' | '/' | '/fabrics' | '/results' | '/size'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FabricsRoute: typeof FabricsRoute
  ResultsRoute: typeof ResultsRoute
  SizeRoute: typeof SizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/size': {
      id: '/size'
      path: '/size'
      fullPath: '/size'
      preLoaderRoute: typeof SizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrics': {
      id: '/fabrics'
      path: '/fabrics'
      fullPath: '/fabrics'
      preLoaderRoute: typeof FabricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FabricsRoute: FabricsRoute,
  ResultsRoute: ResultsRoute,
  SizeRoute: SizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
